### ISSUE TITLE
Building the C library 

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/CaosDB.jl#1]
we need a `Makefile`, that goes like:
```
$(CPP) -Wall -Wall -fPIC -shared -lcurl $(LDFLAGS) -o libcaoslib.$(I_DONT_REMEMBER_THE_VARIABLE_FOR_THE_EXTENSION) caoslib.cpp
```

Then Mose Giordano says :
for a single line like that in the end you can just write it in the script, like this: https://github.com/giordano/CubaBuilder/blob/master/build_tarballs.jl#L17

you'll run some commands in the shell of the wizard (the wizard of the [BinaryBuilder.jl](https://juliapackaging.github.io/BinaryBuilder.jl/latest/#BinaryBuilder.jl-1)), that will be the build script
have a look at this script: https://github.com/robertdj/DeldirBuilder/blob/master/build_tarballs.jl#L16
the variable for the extension is `${dlext}`
this script doesn't use a Makefile, does everything within the script

**Comment by salexan2001** [comment]
I am dropping the C library, all functions use native julia code now.
